// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CarModels
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("filteredOn")]
        public string[] FilteredOn { get; set; }

        [JsonProperty("cars")]
        public Car[] Cars { get; set; }
    }

    public partial class Car
    {
        [JsonProperty("Make")]
        public string Make { get; set; }

        [JsonProperty("CityMPG")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CityMpg { get; set; }

        [JsonProperty("CityELEC")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CityElec { get; set; }

        [JsonProperty("CombMPG")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CombMpg { get; set; }

        [JsonProperty("CombELEC")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long CombElec { get; set; }

        [JsonProperty("Cyl")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Cyl { get; set; }

        [JsonProperty("Displace")]
        public string Displace { get; set; }

        [JsonProperty("Drive")]
        public string Drive { get; set; }

        [JsonProperty("Fuel")]
        public string Fuel { get; set; }

        [JsonProperty("HighwELEC")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long HighwElec { get; set; }

        [JsonProperty("HighwMPG")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long HighwMpg { get; set; }

        [JsonProperty("Trans")]
        public string Trans { get; set; }

        [JsonProperty("Size")]
        public string Size { get; set; }

        [JsonProperty("Year")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Year { get; set; }

        [JsonProperty("Trim")]
        public string Trim { get; set; }

        [JsonProperty("Model")]
        public string Model { get; set; }
    }
}
